name: ShellCheck

on:
  push:
    branches:
      - main  # or your default branch name
    paths:
      - '**/*.sh'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.sh'

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install ShellCheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck

    - name: Run check.sh and store results
      run: |
        sh ./scripts/check.sh -f checkstyle > shellcheck-results.xml

    - uses: staabm/annotate-pull-request-from-checkstyle-action@v1
      with:
        files: shellcheck-results.xml
        notices-as-warnings: true

    - name: Check ShellCheck Results
      run: |
        if [ -s shellcheck-results.xml ]; then
          echo "ShellCheck found issues"
          exit 1
        else
          echo "All scripts passed shellcheck"
        fi

