name: ShellCheck

on:
  push:
    paths:
      - '**/*.sh'
  pull_request:
    paths:
      - '**/*.sh'

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install ShellCheck
      run: sudo apt-get install -y shellcheck

    - name: Run check.sh
      run: |
        chmod +x ./scripts/check.sh
        ./scripts/check.sh
