name: ShellCheck

on:
  push:
    branches:
      - main  # or your default branch name
    paths:
      - '**/*.sh'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.sh'

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install ShellCheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck

    - name: Run check.sh
      run: |
        chmod +x ./scripts/check.sh
        ./scripts/check.sh -f checkstyle > shellcheck-results.xml

    - name: Annotate ShellCheck Results
      uses: reviewdog/action-shellcheck@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        path: "."
        pattern: "*.sh"
        fail_on_error: true

    - name: Upload ShellCheck Results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: shellcheck-results
        path: shellcheck-results.xml

    - name: Check ShellCheck Results
      run: |
        if [ -s shellcheck-results.xml ]; then
          echo "ShellCheck found issues"
          exit 1
        else
          echo "All scripts passed shellcheck"
        fi
